on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release provider

jobs:
  build:
    name: Release provider
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: make release
        continue-on-error: true
        
      - name: Create Release
        uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            terraform-provider-sysdig-darwin-386.tar.gz
            terraform-provider-sysdig-darwin-amd64.tar.gz
            terraform-provider-sysdig-linux-386.tar.gz
            terraform-provider-sysdig-linux-amd64.tar.gz
            terraform-provider-sysdig-linux-arm64.tar.gz
            terraform-provider-sysdig-linux-arm.tar.gz
            terraform-provider-sysdig-linux-mips64le.tar.gz
            terraform-provider-sysdig-linux-mips64.tar.gz
            terraform-provider-sysdig-linux-mipsle.tar.gz
            terraform-provider-sysdig-linux-mips.tar.gz
            terraform-provider-sysdig-linux-ppc64le.tar.gz
            terraform-provider-sysdig-linux-ppc64.tar.gz
            terraform-provider-sysdig-linux-riscv64.tar.gz
            terraform-provider-sysdig-linux-s390x.tar.gz
            terraform-provider-sysdig-windows-386.tar.gz
            terraform-provider-sysdig-windows-amd64.tar.gz
            terraform-provider-sysdig-windows-arm.tar.gz
          draft: true
          prerelease: false
